# Generated by Django 5.2.3 on 2025-06-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingSession',
        ),
    ]
