# Generated by Django 5.2.3 on 2025-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('door', '0006_delete_locksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], max_length=10)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
    ]
