# Generated by Django 5.2.3 on 2025-06-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dooraccess',
            name='user_id',
        ),
    ]
