# Generated by Django 5.2.3 on 2025-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0008_remove_dooraccess_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dooraccess',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
